version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - product-service-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: product-service-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - product-service-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: product-service-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: product_service
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: product_user
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - product-service-network

networks:
  product-service-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

